[proxy]
host = "hypixel.net"
version = "1.8.9"
port = 25_566

[settings]
prefix = "/"
locale = "en-UK"

[modules]
lunarMods = true
mvpEmojis = true
ezBypass = false
parkourTimer = false
locraw = true
logChat = true

[commands]
test = true
reload = true
toggle = true
debug = true
