[proxy]
host = "hypixel.net"
version = "1.8.9"
port = 25_566

[settings]
prefix = "/"
locale = "en-UK"

[modules]
mvpEmojis = false
ezBypass = false
parkourTimer = false
packetFilter = true
owoSpeak = false
wonkyText = false
leetSpeak = false
pirateSpeak = false
reversedText = false

[commands]
test = true
reload = true
toggle = true
debug = true
